"""Generate jsport/src/symbols.h from port/js_symbols.csv (JS_CDROM.EXE, flat LE image).

functions (address < 0x80000, code objects)   #define FN_<name> 0xXXXXXXXXu  (for comments / traces)
globals   (address >= 0x80000, data object)   #define G_<name>  0xXXXXXXXXu  (flat address in the exe;
                                              offset into the data-segment image = G_x - DSEG_BASE)
Duplicate names get an address suffix. Module, confidence and note are kept as a comment.

    python tools/gen_symbols.py
"""
import csv, os, re
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'port', 'js_symbols.csv')
DST = os.path.join(ROOT, 'jsport', 'src', 'symbols.h')
DATA_BASE = 0x80000

rows = list(csv.DictReader(open(SRC, encoding='utf-8', errors='replace')))


def ident(name):
    name = re.sub(r'\W', '_', name)
    return ('_' + name) if name[:1].isdigit() else name


def comment(r):
    note = (r.get('note') or '').replace('*/', '* /').replace('/*', '/ *')
    if len(note) > 70:
        note = note[:67] + '...'
    return '/* %s%s */' % (r['module'], (', ' + note) if note else '')


def gname(r, prefix):
    n = ident(r['name'])
    return n[2:] if prefix == 'G_' and n.startswith('g_') and len(n) > 2 else n


for r in rows:
    r['addr'] = int(r['address'], 16)
fn = sorted((r for r in rows if r['addr'] < DATA_BASE), key=lambda r: r['addr'])
gl = sorted((r for r in rows if r['addr'] >= DATA_BASE), key=lambda r: r['addr'])

out = ['/* Generated by tools/gen_symbols.py from port/js_symbols.csv. Do not edit. */',
       '#pragma once', '',
       '#define DSEG_BASE 0x80000u   /* data object 5 of JS_CDROM.EXE: 0x80000-0x94750 */', '']
for title, sel, prefix in (('Original functions (flat address in JS_CDROM.EXE)', fn, 'FN_'),
                           ('Original globals (flat address; data-segment image offset = G_x - DSEG_BASE)', gl, 'G_')):
    counts = Counter(gname(r, prefix) for r in sel)
    out.append('/* ---- %s */' % title)
    for r in sel:
        n = gname(r, prefix)
        if counts[n] > 1:
            n = '%s_%05X' % (n, r['addr'])
        out.append('#define %-44s 0x%08Xu  %s' % (prefix + n, r['addr'], comment(r)))
    out.append('')

os.makedirs(os.path.dirname(DST), exist_ok=True)
open(DST, 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
print('wrote %s: %d functions, %d globals' % (DST, len(fn), len(gl)))
